volumes:
  embla_local_postgres_data: {}
  embla_local_postgres_data_backups: {}
  embla_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: embla_local_django
    container_name: embla_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: embla_production_postgres
    container_name: embla_local_postgres
    volumes:
      - embla_local_postgres_data:/var/lib/postgresql/18/docker
      - embla_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: embla_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: embla_local_redis
    volumes:
      - embla_local_redis_data:/data

  celeryworker:
    <<: *django
    image: embla_local_celeryworker
    container_name: embla_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: embla_local_celerybeat
    container_name: embla_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: embla_local_flower
    container_name: embla_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: embla_local_frontend
    container_name: embla_local_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django
